"""initial create portfolios and transactions tables

Revision ID: fc0649d78c41
Revises: 
Create Date: 2026-03-07 17:25:10.895311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0649d78c41'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_id'), ['id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.alter_column('transaction_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('portfolio_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_id'))

    # ### end Alembic commands ###